apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: running-clam-go
  janus-idp.io/tekton: running-clam-go
  backstage.io/kubernetes-id: running-clam-go
  backstage.io/kubernetes-namespace: rhtap-dmo 
  app.kubernetes.io/part-of: running-clam-go
resources: 
- deployment.yaml
- route.yaml
- service.yaml
